version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: guru_DB
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: guruuser
      MYSQL_PASSWORD: gurupassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  backend:
    build: ./backend
    environment:
      DATABASE_URL: mysql+pymysql://guruuser:gurupassword@db:3306/guru_DB
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data:
